In [4]:
import tensorflow as tf
# Initialize two constants
x1 = tf.constant([10,18,6,40])
x2 = tf.constant([5,6,7,8])

# basic math operations
a=tf.add(x1,x2)
b=tf.subtract(x1,x2)
c=tf.multiply(x1,x2)
d=tf.divide(x1,x2)

# Print the result
print(a)
print(b)
print(c)
print(d)
# print the name and USN number
name = input("Enter your name: ")
print(name)
USN = input("Enter your USN: ")
print(USN)

tf.Tensor([15 24 13 48], shape=(4,), dtype=int32)
tf.Tensor([ 5 12 -1 32], shape=(4,), dtype=int32)
tf.Tensor([ 50 108  42 320], shape=(4,), dtype=int32)
tf.Tensor([2.         3.         0.85714286 5.        ], shape=(4,), dtype=float64)
Enter your name: A
A
Enter your USN: 45
45
